
name: Coredns

on:
  push:
    branches: [ main ]
    paths:
    - 'DifferentialTesting/Implementations/Coredns/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'DifferentialTesting/Implementations/Coredns/**'

jobs:
  Coredns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |-
          cd DifferentialTesting/Implementations
          DOCKER_BUILDKIT=1 docker build -t coredns:oct -f Coredns/Dockerfile .
      
      - name: Start DNS Service
        run: |-
          cd DifferentialTesting/Implementations
          python main.py -i coredns -p 8500
                  
      - name: Test a query
        run: dig @127.0.0.1 -p 8500 +norecurse host1.campus.edu