
name: Powerdns

on:
  push:
    branches: [ main ]
    paths:
    - 'DifferentialTesting/Implementations/Powerdns/**'
  pull_request:
    branches: [ main ]
    paths:
    - 'DifferentialTesting/Implementations/Powerdns/**'

jobs:
  Powerdns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |-
          cd DifferentialTesting/Implementations
          DOCKER_BUILDKIT=1 docker build -t powerdns:oct -f Powerdns/Dockerfile .
      
      - name: Start DNS Service
        run: |-
          cd DifferentialTesting/Implementations
          python main.py -i powerdns -p 8300
        
      - name: Test a query
        run: dig @127.0.0.1 -p 8300 +norecurse host1.campus.edu