
name: Zen

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
    - 'TestGenerator/**'
    -  '!**/README.md'
  pull_request:
    branches: [ main ]
    paths:
    - 'TestGenerator/**'
  

jobs:
  Zen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: csharp, python
          
      - name: Build the project
        run: dotnet build TestGenerator
      
      - name: Add Msbuild package
        run: |-
          cd TestGenerator/Tests
          dotnet add package coverlet.msbuild
        
      - name: Run tests
        run: dotnet test TestGenerator /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: TestGenerator/Tests/coverage.opencover.xml
          fail_ci_if_error: true
